#!/bin/bash

# Ecotron Deployment Script - ad landing v1

echo "🚀 Starting Ecotron Deployment..."

# 1. Check for .env file
if [ ! -f .env ]; then
    echo "❌ .env file not found! Please create it from .env.production.example"
    exit 1
fi

# 2. Pull latest images and build
echo "📦 Building production containers..."
docker-compose -f docker-compose.prod.yml build

# 3. Spin up the stack
echo "⚡ Starting services..."
docker-compose -f docker-compose.prod.yml up -d

# 4. Initialize Ollama model
echo "🧠 Initializing AI model (Phi3)..."
# Wait for Ollama to be ready
sleep 10
docker exec -it ecotron-ollama ollama pull phi3

echo "✅ Deployment Complete!"
echo "🌍 Your site should be live at https://ecotron.co.in"
echo "🔐 SSL Certificates are being automatically generated by Caddy."
